---

- name: start-kernel-ci-backend
  service:  name={{ init_service }}
            state=started

- name: restart-kernel-ci-backend
  service:  name={{ init_service }}
            state=restarted

- name: stop-kernel-ci-backend
  service:  name={{ init_service }}
            state=stopped

- name: stop-celery
  service:  name=kernelci-{{ kci_app_name }}-celery
            state=stopped

- name: start-celery
  service:  name=kernelci-{{ kci_app_name }}-celery
            state=started

- name: restart-celery
  service:  name=kernelci-{{ kci_app_name }}-celery
            state=restarted

- name: reload-systemd
  command: /bin/systemctl daemon-reload
